#配置端口号
server:
  port: 8090

#配置数据源信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wms?characterEncoding=utf-8&userSSL=false
    username: root
    password: 1516987

#开启日志功能
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
